In [1]:
!pip install osmnx

import osmnx as ox
import pandas as pd

ox.settings.use_cache = True
ox.settings.log_console = True

Requirement already satisfied: osmnx in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.1.0)
Requirement already satisfied: geopandas>=1.0.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from osmnx) (1.1.3)
Requirement already satisfied: networkx>=2.5 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from osmnx) (3.6.1)
Requirement already satisfied: numpy>=1.24 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from osmnx) (2.3.0)
Requirement already satisfied: pandas>=1.5 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from osmnx) (2.2.3)
Requirement already satisfied: requests>=2.30 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from osmnx) (2.32.3)
Requirement already satisfied: shapely>=2.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from osmnx) (2.1.2)
Requirement already satisfied: pyogrio>=0.7.2 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from geopandas>=1.0.1->osmnx) (0.12.1)
Requirement already satisfied: packaging in C:\Users\LENOVO\AppData\Roaming\Python\Python311\site-packages (from geopandas>=1.0.1->osmnx) (25.0)
Requirement already satisfied: pyproj>=3.5.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from geopandas>=1.0.1->osmnx) (3.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\LENOVO\AppData\Roaming\Python\Python311\site-packages (from pandas>=1.5->osmnx) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas>=1.5->osmnx) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas>=1.5->osmnx) (2025.2)
Requirement already satisfied: certifi in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pyogrio>=0.7.2->geopandas>=1.0.1->osmnx) (2025.4.26)
Requirement already satisfied: six>=1.5 in C:\Users\LENOVO\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas>=1.5->osmnx) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests>=2.30->osmnx) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests>=2.30->osmnx) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests>=2.30->osmnx) (2.4.0)

In [2]:
# Tai data metro St.Peterburg
place = "Saint Petersburg, Russia"

tags_station = {
    "railway": "station",
    "station": "subway"
}

stations = ox.features_from_place(place, tags_station)

# lọc chỉ lấy Point
stations = stations[stations.geometry.type == "Point"]

print("Số ga:", len(stations))
stations.head()

Số ga: 136

                                   geometry esr:user  \
element id
node    308112    POINT (30.35477 59.99046)   037405
        308149     POINT (30.42501 59.9882)   037024
        7535181   POINT (30.35816 59.95818)   038205
        21596808  POINT (30.36311 59.92737)   031812
        21683296  POINT (30.33062 59.91879)   033061

                                         name                    name:en  \
element id
node    308112                      Кушелевка                 Kushelevka
        308149                     Пискарёвка                Piskaryovka
        7535181   Санкт-Петербург-Финляндский  St Petersburg–Finlyandsky
        21596808      Санкт-Петербург-Главный      St. Petersburg Glavny
        21683296    Санкт-Петербург-Витебский                        NaN

                                      network            network:en  \
element id
node    308112                            NaN                   NaN
        308149                            NaN                   NaN
        7535181                           NaN                   NaN
        21596808  Октябрьская железная дорога  Oktyabrskaya Railway
        21683296                          NaN                   NaN

                                   network:ru network:wikidata  \
element id
node    308112                            NaN              NaN
        308149                            NaN              NaN
        7535181                           NaN              NaN
        21596808  Октябрьская железная дорога         Q1327441
        21683296                          NaN              NaN

                                                               note  \
element id
node    308112                                                  NaN
        308149                                                  NaN
        7535181                                                 NaN
        21596808  в билетах на поезда указывается станция отправ...
        21683296                                                NaN

                            official_name  ...                      website  \
element id                                 ...
node    308112                        NaN  ...                          NaN
        308149                        NaN  ...                          NaN
        7535181                       NaN  ...  http://finlyandsky.dzvr.ru/
        21596808  Санкт-Петербург-Главный  ...                          NaN
        21683296                      NaN  ...                          NaN

                 opening_hours phone tourism old_name:fi old_name:ru  \
element id
node    308112             NaN   NaN     NaN         NaN         NaN
        308149             NaN   NaN     NaN         NaN         NaN
        7535181            NaN   NaN     NaN         NaN         NaN
        21596808           NaN   NaN     NaN         NaN         NaN
        21683296           NaN   NaN     NaN         NaN         NaN

                 internet_access internet_access:fee name:et name:sv
element id
node    308112               NaN                 NaN     NaN     NaN
        308149               NaN                 NaN     NaN     NaN
        7535181              NaN                 NaN     NaN     NaN
        21596808             NaN                 NaN     NaN     NaN
        21683296             NaN                 NaN     NaN     NaN

[5 rows x 66 columns]

In [3]:
# Tai tuyen metro
tags_lines = {
    "railway": "subway"
}

lines = ox.features_from_place(place, tags_lines)

print("Số tuyến:", len(lines))

Số tuyến: 936

In [4]:
# lấy lat lon
stations["lat"] = stations.geometry.y
stations["lon"] = stations.geometry.x

# giữ cột cần thiết
stations_clean = stations[["name", "lat", "lon"]].reset_index(drop=True)

# thêm id
stations_clean["id"] = stations_clean.index

stations_clean.head()

                          name        lat        lon  id
0                    Кушелевка  59.990464  30.354767   0
1                   Пискарёвка  59.988203  30.425010   1
2  Санкт-Петербург-Финляндский  59.958182  30.358157   2
3      Санкт-Петербург-Главный  59.927368  30.363110   3
4    Санкт-Петербург-Витебский  59.918791  30.330624   4